# **************************************************************************
# *
# * Authors: Yunior C. Fonseca Reyna    (cfonseca@cnb.csic.es)
# *
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

from pyworkflow import BETA
from pyworkflow.protocol.params import (PointerParam, FloatParam, BooleanParam, FileParam, StringParam)
from . import ProtCryosparcBase
from ..convert import *
from ..utils import *
from ..constants import *


class ProtCryoSparc3DFlexMeshPrepare(ProtCryosparcBase):
    """
    Prepares particles for use in 3DFlex training and reconstruction. At the same
    way, Takes in a consensus (rigid) refinement density map, plus optionally
    a segmentation and generates a tetrahedral mesh for 3DFlex.
    """

    """
        Prepares tetrahedral meshes for CryoSPARC 3D Flex training and reconstruction workflows.
        The protocol takes as input a consensus density map generated during the 3D Flex Data
        Preparation stage and optionally a segmentation mask, producing a deformable tetrahedral
        mesh representation suitable for modeling continuous structural heterogeneity.

        AI Generated:

        3D Flex Mesh Prepare (ProtCryoSparc3DFlexMeshPrepare) — User Manual
            Overview

            The 3D Flex Mesh Prepare protocol generates the deformable tetrahedral mesh used by
            CryoSPARC 3D Flex to model continuous conformational variability in cryo-EM datasets.
            Rather than working directly on voxel densities alone, 3D Flex represents molecular
            motion through a mesh-based deformation model capable of describing flexible structural
            transitions in a physically coherent manner.

            In practical cryo-EM workflows, this protocol is executed after the 3D Flex Data
            Preparation step and before 3D Flex Training. Its main objective is to transform the
            consensus reconstruction into a geometric representation that defines how different
            regions of the structure may deform during learning and reconstruction.

            From a biological perspective, the generated mesh strongly influences the quality,
            realism, and interpretability of the resulting motion trajectories. Proper mesh
            preparation is therefore essential when studying flexible assemblies, conformational
            landscapes, or dynamic molecular machines.

            Inputs and General Workflow

            The protocol requires as primary input the output generated by the 3D Flex Data
            Preparation protocol, including the prepared consensus volume. Optionally, the user
            may provide a binary mask defining the molecular region of interest. If no mask is
            supplied, the protocol automatically generates a solvent mask from the consensus map
            through filtering, thresholding, dilation, and soft padding operations.

            The workflow constructs a tetrahedral mesh covering the molecular volume. This mesh
            acts as the deformation framework used during 3D Flex training to describe structural
            motion. The mesh may represent the structure globally or be subdivided into biologically
            meaningful regions using segmentation inputs.

            The protocol also supports the incorporation of segmentation information generated from
            external tools such as UCSF Chimera Segger. This allows the mesh to be partitioned into
            subdomains corresponding to independent structural regions, enabling more biologically
            realistic deformation behavior.

            Solvent Mask Preparation

            When no external mask is provided, the protocol automatically computes a solvent mask
            from the consensus density map. The volume is first low-pass filtered to suppress
            high-frequency noise and facilitate stable thresholding. The filtered map is then
            thresholded to isolate the molecular envelope, followed by dilation and soft padding
            to generate a smooth solvent boundary.

            From a biological perspective, the solvent mask determines which regions contribute to
            mesh generation and deformation modeling. Accurate masking is particularly important
            for flexible complexes, membrane proteins, and assemblies with peripheral domains,
            where poorly defined solvent regions may introduce unstable or biologically meaningless
            deformations.

            The filtering resolution, threshold level, dilation radius, and soft padding parameters
            collectively control the final molecular envelope. Conservative masking generally
            produces more stable meshes, whereas overly permissive masks may allow unrealistic
            flexibility in low-density solvent regions.

            Mesh Construction and Tetrahedral Resolution

            The core of the protocol is the generation of a tetrahedral mesh describing the spatial
            organization of the molecular structure. The user controls mesh granularity through the
            number of tetrahedral cells distributed across the box dimensions.

            A higher tetrahedral density produces a finer mesh capable of representing smaller and
            more localized motions. This may improve flexibility modeling in highly dynamic systems,
            although it also increases computational cost and may increase sensitivity to noise or
            overfitting. Lower mesh densities generate smoother and more stable deformations but
            may fail to capture localized conformational variability.

            In biological applications, choosing the mesh resolution depends on the complexity of
            the molecular system and the expected motion scale. Large ribonucleoprotein complexes,
            molecular motors, or multi-domain assemblies often benefit from finer meshes, whereas
            relatively rigid particles may require only coarse deformation models.

            Segmentation and Subdomain Modeling

            The protocol optionally supports segmentation-driven mesh subdivision. External
            segmentation files may define independent structural regions that are converted into
            submeshes before being fused into a final unified mesh.

            This functionality is particularly important for biological systems composed of multiple
            domains or subunits exhibiting semi-independent motion. By separating flexible regions
            into dedicated mesh components, the deformation model can better preserve biologically
            meaningful boundaries between moving domains.

            Segment connection definitions specify how independent regions are fused into a valid
            deformation tree. These relationships prevent disconnected or cyclic mesh structures
            and ensure physically coherent motion propagation during training.

            Additionally, selected regions may be declared rigid. Rigid segments receive increased
            rigidity weighting, reducing unrealistic internal deformation while still allowing
            movement relative to neighboring domains. This feature is especially useful for compact
            structural cores or experimentally validated rigid bodies.

            Rigidity Weighting and Motion Regularization

            The protocol includes rigidity weighting mechanisms designed to regulate how different
            regions deform during 3D Flex training. Dense structural regions are assigned higher
            rigidity values, while low-density or solvent regions receive lower rigidity penalties.

            Biologically, this helps the deformation model focus flexibility on plausible molecular
            motions rather than introducing unrealistic distortions within well-resolved structural
            cores. Empty regions surrounding the molecule remain more deformable, allowing the mesh
            to adapt without excessively perturbing protein density.

            An optional stiffening mode further increases rigidity in peripheral low-density regions.
            This is particularly useful for small particles or low signal-to-noise datasets where
            poorly constrained outer regions may otherwise become unstable during training.

            However, excessive rigidification may oversmooth biologically meaningful transitions
            between domains and reduce the ability of the model to capture localized flexibility.
            Careful parameter tuning is therefore important depending on the biological question
            and data quality.

            Outputs and Their Interpretation

            After execution, the protocol generates the tetrahedral mesh representation required
            for 3D Flex Training. The mesh is exported as a PDB representation suitable for
            visualization and inspection within molecular viewers.

            The resulting mesh defines the deformation space used by the neural deformation model
            during continuous heterogeneity analysis. Its topology, rigidity distribution, and
            segmentation structure directly affect the quality and interpretability of learned
            conformational trajectories.

            In practice, users should visually inspect the generated mesh before proceeding to
            training. Unrealistic mesh boundaries, disconnected regions, or excessive solvent
            coverage may negatively affect downstream reconstruction quality.

            Practical Recommendations

            For most standard cryo-EM workflows, automatic solvent mask generation with moderate
            tetrahedral density provides a suitable starting point. When working with highly
            flexible or multi-domain systems, introducing biologically informed segmentation files
            significantly improves deformation realism.

            Smaller and noisier datasets often benefit from increased rigidity weighting to reduce
            overfitting and stabilize motion learning. Conversely, highly dynamic systems may
            require finer meshes and reduced rigidity constraints to accurately capture continuous
            conformational variability.

            Visual inspection of the generated mesh is strongly recommended before initiating
            3D Flex Training, particularly in cases involving segmentation-driven submeshes or
            rigid body assignments.

            Final Perspective

            In modern cryo-EM analysis, understanding molecular flexibility requires not only
            high-resolution density maps but also physically meaningful deformation models.
            The 3D Flex Mesh Prepare protocol provides the structural framework enabling
            CryoSPARC 3D Flex to represent continuous molecular motion in a biologically
            interpretable manner.

            Appropriate solvent masking, biologically informed segmentation, and carefully
            balanced rigidity weighting are the key factors that determine whether the resulting
            deformation model captures meaningful structural dynamics or introduces artificial
            motion artifacts.
        """
    _label = '3D flex mesh prepare'
    _devStatus = BETA
    _protCompatibility = [V4_1_0, V4_1_1, V4_1_2, V4_2_0, V4_2_1, V4_3_1,
                          V4_4_0, V4_4_1, V4_5_1, V4_5_3, V4_6_0, V4_6_1, V4_6_2, V4_7_0,
                          V4_7_1]

    # --------------------------- DEFINE param functions ----------------------
    def _defineFileNames(self):
        """ Centralize how files are called within the protocol. """
        myDict = {
            'input_particles': self._getTmpPath('input_particles.star'),
            'out_particles': self._getPath() + '/output_particle.star',
            'stream_log': self._getPath() + '/stream.log'
        }
        self._updateFilenamesDict(myDict)

    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('dataPrepare', PointerParam,
                      pointerClass='ProtCryoSparc3DFlexDataPrepare',
                      label="Data prepare protocol",
                      important=True,
                      help='Prepared particles and consensus volume from the 3D flex data prepare protocol.')
        form.addParam('refMask', PointerParam, pointerClass='VolumeMask',
                      default=None,
                      label='Input Mask',
                      allowsNull=True,
                      help='Mask raw data')

        form.addSection(label='Mesh Prepare')

        solventMaskGroup = form.addGroup('Solvent mask preparation',
                                         condition="refMask is None")
        solventMaskGroup.addParam('mask_in_lowpass_A', IntParam, default=10,
                                  condition="refMask is None",
                                  label="Filter input volume res. (A)",
                                  help="Filter the input consensus reconstruction "
                                       "volume to this resolution (A) before thresholding "
                                       "to create the outer solvent mask. Solvent mask is"
                                       " only generated if it is not already input.")

        solventMaskGroup.addParam('mask_in_threshold_level', FloatParam, default=0.5,
                                  condition="refMask is None",
                                  label="Mask threshold",
                                  help="Threshold the input consensus reconstruction "
                                       "volume (after filtering) at this absolute "
                                       "density level to make the solvent mask. "
                                       "Solvent mask is only generated if it is "
                                       "not already input.")

        solventMaskGroup.addParam('mask_dilate_A', IntParam,
                                  default=2,
                                  condition="refMask is None",
                                  label="Mask dilation (A)",
                                  help="After thresholding, dilate by this much"
                                       " (A) to create solvent mask")

        solventMaskGroup.addParam('mask_pad_A', IntParam,
                                  default=5,
                                  condition="refMask is None",
                                  label="Mask soft padding (A)",
                                  help="After thresholding and dilation, soft "
                                       "pad by this much (A) to create solvent mask")

        meshPreparationGroup = form.addGroup('Mesh preparation')
        meshPreparationGroup.addParam('tetra_num_cells', IntParam,
                                  default=20,
                                  label="Base num. tetra cells",
                                  help="Number of tetrahedral cells that fit "
                                       "across the extent of the box. Use this "
                                       "to set the size of mesh elements. If "
                                       "set to e.g. 20, the base tetramesh will"
                                       " have elements that are the right size "
                                       "to create a spacing of 20 tetra elements "
                                       "across the box extent in each x,y,z "
                                       "direction. A higher number makes a finer mesh.")

        meshPreparationGroup.addParam('tetra_segments_path', FileParam,
                                      allowsNull=True,
                                      default=None,
                                      label="Segmentation file path",
                                      help="Absolute path to a segmentation file "
                                           "in either .seg format from UCSF "
                                           "Chimera Segger tool or else .mrc format "
                                           "(see CryoSPARC guide for details), "
                                           "defining subdomain regions that "
                                           "should each have a submesh. "
                                           "Submeshes are fused to make final "
                                           "mesh using the segment connections list.")

        meshPreparationGroup.addParam('tetra_segments_fuse_list', StringParam,
                                      allowsNull=True,
                                      default=None,
                                      label="Segment connections",
                                      help="A comma and '>' separated list of "
                                           "connections between segments to use when "
                                           "fusing sub-meshes to make the final mesh. "
                                           "See CryoSPARC guide for full explanation. "
                                           "For example, '0>3, 0>4, 3>2, 2>1' is a valid connection"
                                           " string. Each pair X>Y denotes that segment Y is "
                                           "joined to segment X. The connections must form "
                                           "a 'tree' structure and cannot have cycles. "
                                           "The first pair X>Y must start with the "
                                           "root of the tree as X. The connections "
                                           "must be in breadth-first order of the tree. "
                                           "When using Chimera Segger segmentation input, "
                                           "the X>Y numbers should be region_ids from Segger (e.g., 948>947)")

        meshPreparationGroup.addParam('tetra_rigid_list', StringParam,
                                      allowsNull=True,
                                      default=None,
                                      label="Rigid segments",
                                      help="A comma separated list of segments to make "
                                           "rigid. This is done by setting the rigidity "
                                           "weight of tetra elements for this region to 20. ")


        rigidityWeighting = form.addGroup('Rigidity weighting')
        rigidityWeighting.addParam('rigidity_penalty_min', FloatParam,
                                      default=0.5,
                                      label="Min. rigidity weight",
                                      help="Rigidity weights of tetra elements"
                                           " are 1.0 in the most dense regions "
                                           "of the input consensus map, and fall "
                                           "off to this value (default 0.5) in the"
                                           " least dense/empty regions. This helps "
                                           "encourage the deformation model to expand/contract"
                                           " empty space without distorting the protein density.")

        rigidityWeighting.addParam('rigidity_penalty_stiffen_low_density', BooleanParam,
                                   default=False,
                                   label="Stiffen low density regions",
                                   help="Turning this on will cause the rigidity"
                                        " weights of tetra elements at the periphery "
                                        "of the input consensus density to be increased to 3.0 . "
                                        "Empty regions will still have low rigidity, but non-empty "
                                        "regions at the periphery of the structure will be rigidified."
                                        " This helps to combat overfitting in smaller particles or"
                                        " poor SNR data where otherwise low density peripheral "
                                        "features start to 'fly around'. However, it can also cause "
                                        "the deformations to be overly smooth and blur motion 'boundaries between domains. ")


        # --------------[Compute settings]---------------------------
        form.addSection(label="Compute settings")
        addComputeSectionParams(form, allowMultipleGPUs=False, needGPU=False)

    def _insertAllSteps(self):
        self._defineFileNames()
        self._defineParamsPrepareName()
        self._defineParamsMeshName()
        self._initializeCryosparcProject()
        self._insertFunctionStep(self.convertInputStep)
        self._insertFunctionStep(self.mergePrepareStep)
        self._insertFunctionStep(self.createOutputStep)

    # --------------------------- STEPS functions ------------------------------
    def mergePrepareStep(self):
        self.info(pwutils.yellowStr("3D Flex Mesh Preparation started..."))
        self.doRun3DFlexMeshPrepare()

    def createOutputStep(self):
        """
        Create the protocol output. Convert cryosparc file to Relion file
        """
        # save pdb file with mesh
        # this will not be scipion output
        # I just want to display it in the viewer
        jobId = self.run3DFlexMeshPrep
        csOutputFolder = os.path.join(self.projectDir.get(),
                                       self.run3DFlexMeshPrep.get())
        pdbMeshName = "%s_mesh_pdb.pdb" % jobId
        csOutputFolder = os.path.join(self.projectDir.get(),
                                      self.run3DFlexMeshPrep.get())
        copyFiles(csOutputFolder, self._getExtraPath(), files=[pdbMeshName])
    # ------------------------- Utils methods ----------------------------------

    def _fillDataFromIter(self, imgSet):
        outImgsFn = 'particles@' + self._getFileName('out_particles')
        imgSet.setAlignmentProj()
        imgSet.copyItems(self._getInputParticles(),
                         updateItemCallback=self._createItemMatrix,
                         itemDataIterator=emtable.Table.iterRows(fileName=outImgsFn))

    def _createItemMatrix(self, particle, row):
        createItemMatrix(particle, row, align=ALIGN_PROJ)
        setCryosparcAttributes(particle, row, RELIONCOLUMNS.rlnRandomSubset.value)

    def _validate(self):
        validateMsgs = cryosparcValidate()
        if not validateMsgs:
            mask = self.refMask.get()
            if mask:
                maskDim = mask.getDim()
                dataPrepareProt = self.dataPrepare.get()
                if dataPrepareProt:
                    if hasattr(dataPrepareProt, 'outputVolume'):
                        outputVolumeDim = dataPrepareProt.outputVolume.getDim()
                        if maskDim != outputVolumeDim:
                            validateMsgs.append('The dimension of the mask must be %s according to the 3D Flex data prepare protocol(Training box size parameter)' % str(outputVolumeDim) )
                else:
                    validateMsgs.append('You need to specify the 3D Flex Data Prepare protocol')

        return validateMsgs

    def _defineParamsPrepareName(self):
        """ Define a list with 3D Flex Prepare Data parameters names"""
        self._paramsPrepareName = ['box_size_pix', 'bin_size_pix', 'alpha_min',
                            'keep_num_particles']
        self.lane = str(self.getAttributeValue('compute_lane'))

    def _defineParamsMeshName(self):
        """ Define a list with 3D Flex Mesh Prepare parameters names"""
        self._maskMeshPrepareName = ['mask_in_lowpass_A', 'mask_in_threshold_level',
                                     'mask_dilate_A', 'mask_pad_A']
        self._paramsMeshName = ['tetra_num_cells', 'tetra_segments_path',
                                'tetra_segments_fuse_list', 'tetra_rigid_list',
                                'rigidity_penalty_min',
                                'rigidity_penalty_stiffen_low_density']
        self.lane = str(self.getAttributeValue('compute_lane'))

    def doRun3DFlexMeshPrepare(self):
        self._className = 'flex_meshprep'
        params = {}
        varDataPrepJob = str(self.dataPrepare.get().run3DFlexDataPrepJob)
        input_group_connect = {"volume": str('%s.volume' % varDataPrepJob)}

        if self.refMask.get() is not None:
            input_group_connect["mask"] = str(self.mask)
        else:
            for paramName in self._maskMeshPrepareName:
                if self.getAttributeValue(paramName) is not None:
                    params[str(paramName)] = str(self.getAttributeValue(paramName))

        for paramName in self._paramsMeshName:
            if self.getAttributeValue(paramName) is not None:
                params[str(paramName)] = str(self.getAttributeValue(paramName))

        run3DFlexMeshPrepJob = enqueueJob(self._className,
                                          self.projectName.get(),
                                          self.workSpaceName.get(),
                                          str(params).replace('\'', '"'),
                                          str(input_group_connect).replace('\'',
                                                                           '"'),
                                          self.lane, False)

        self.run3DFlexMeshPrep = String(run3DFlexMeshPrepJob.get())
        self.currenJob.set(run3DFlexMeshPrepJob.get())
        self._store(self)

        waitForCryosparc(self.projectName.get(),
                         self.run3DFlexMeshPrep.get(),
                         "An error occurred in the 3D Flex Mesh Preparation process. "
                         "Please, go to cryoSPARC software for more "
                         "details.", self)
        clearIntermediateResults(self.projectName.get(),
                                 self.run3DFlexMeshPrep.get())










