# **************************************************************************
# *
# * Authors: Yunior C. Fonseca Reyna    (cfonseca@cnb.csic.es)
# *
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import os.path
import zipfile

from pwem import getMatchingFiles
from pwem.protocols import ProtFlexBase
from pyworkflow import BETA
from pyworkflow.protocol.params import PointerParam
from . import ProtCryosparcBase
from ..convert import *
from ..utils import *
from ..constants import *


class ProtCryoSparc3DFlexGenerator(ProtCryosparcBase, ProtFlexBase):
    """
    Takes in a checkpoint from training and generates volume series from it, to show what the model is learning
    about the motion of the particle. This job can be run while training is ongoing to see progress along the way.
    This job can also optionally take in a high-resolution density map (e.g., from 3D Flex Reconstruction) and
    will upscale the deformation model and apply deformations to the high resolution map.
    """

    """
    ProtCryoSparc3DFlexGenerator — 3D Flex Volume Generator Protocol

    Overview
    --------
    Generates series of volumes from a trained cryoSPARC 3D Flex model in order
    to visualize and analyze the continuous conformational variability learned
    during training.

    The protocol uses checkpoints generated by a previous 3D Flex Training job
    and reconstructs volume trajectories across latent dimensions, allowing
    users to inspect molecular motions and structural transitions.

    This process is especially useful for:
        - Visualizing continuous flexibility.
        - Interpreting latent-space dynamics.
        - Monitoring training progress.
        - Generating motion trajectories for biological analysis.
        - Producing high-resolution flexible reconstructions.

    Inputs and Workflow
    -------------------
    - 3D Flex Training Protocol:
        * Provides the trained neural deformation model.
        * Supplies latent-space information and learned motion patterns.
        * Must contain valid checkpoint data.

    The workflow follows these stages:
        1. Initialize cryoSPARC project environment.
        2. Connect the trained 3D Flex model.
        3. Configure generation parameters.
        4. Launch cryoSPARC volume generation job.
        5. Wait for job completion.
        6. Copy generated series into the protocol workspace.
        7. Extract generated volume trajectories from ZIP archives.

    Volume Series Generation
    ------------------------
    The protocol generates multiple reconstructed volumes along latent-space
    trajectories learned by the neural model.

    - Frames Per Series:
        * Defines the number of generated volumes.
        * Odd values are recommended to ensure that the neutral latent position
          is located at the center of the trajectory.
        * Higher values produce smoother motion transitions but increase
          computational cost and storage usage.

    Generated trajectories represent continuous structural changes inferred
    from experimental particle heterogeneity.

    cryoSPARC Integration
    ---------------------
    The protocol interfaces directly with cryoSPARC through:
        - Job enqueueing.
        - Model checkpoint connections.
        - GPU resource allocation.
        - Execution monitoring.
        - Automatic synchronization with cryoSPARC projects.

    The generator can be executed while training is still ongoing, enabling
    intermediate inspection of model convergence and learned flexibility.

    GPU and Compute Management
    --------------------------
    - GPU execution is supported and recommended.
    - Compatible with queue-based execution systems.
    - Automatically determines GPU allocation depending on execution mode.
    - Uses cryoSPARC compute lanes for distributed execution environments.

    Output Handling
    ---------------
    After cryoSPARC execution:
        - Generated series are exported as compressed ZIP files.
        - Output archives are copied into the protocol workspace.
        - Volume series are automatically extracted into dedicated folders.
        - Temporary compressed files are removed after extraction.

    The final output consists of multiple ordered volume frames representing
    conformational trajectories across latent dimensions.

    Validation Rules
    ----------------
    Before execution, the protocol validates:
        - cryoSPARC environment compatibility.
        - Availability of trained Flex model checkpoints.
        - Presence of generated latent-space data.

    If no checkpoint data exists yet, execution is prevented until the
    training protocol produces usable outputs.

    Practical Recommendations
    -------------------------
    - Use sufficiently trained 3D Flex models before generation.
    - Choose an odd number of frames for symmetric trajectory sampling.
    - Start with moderate frame counts for quick inspection.
    - Use higher frame counts for smooth visualization movies.
    - Verify generated trajectories against biological expectations.

    Biological Perspective
    ----------------------
    3D Flex generation enables direct visualization of continuous molecular
    motions encoded by neural-network-based cryo-EM heterogeneity analysis.

    The generated trajectories can reveal:
        - Domain motions.
        - Conformational transitions.
        - Flexible regions.
        - Collective structural dynamics.
        - Functional motion pathways.

    These outputs provide biologically meaningful interpretations of
    conformational landscapes that are difficult to observe using traditional
    discrete classification approaches.

    """