# **************************************************************************
# *
# * Authors: Yunior C. Fonseca Reyna    (cfonseca@cnb.csic.es)
# *
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from pyworkflow import BETA
from pyworkflow.protocol.params import (PointerParam, FloatParam, Positive,
                                        BooleanParam, EnumParam)
from pwem.objects import Volume
from pwem.protocols import ProtRefine3D

from . import ProtCryosparcBase
from ..convert import *
from ..utils import *
from ..constants import *


class ProtCryoSparc3DVariability(ProtCryosparcBase, ProtRefine3D):
    """
    Protocol to compute the principle modes of variability with a dataset
    of aligned particles.

    AI Generated:

    3D Variability Analysis (ProtCryoSparc3DVariability) — User Manual
        Overview

        The 3D Variability Analysis protocol is designed to identify and
        characterize continuous structural heterogeneity within a cryo-EM
        dataset composed of aligned particles. Its primary goal is to reveal
        the dominant modes of conformational variability present in a molecular
        system while preserving the overall structural context established
        during refinement.

        In biological research, many macromolecular assemblies do not exist as
        a single rigid structure but instead sample multiple conformations,
        dynamic transitions, or flexible arrangements. This protocol helps
        researchers visualize and interpret these motions by estimating the
        principal directions of structural variability across the dataset.
        These variability modes can provide insight into functional mechanisms,
        ligand interactions, domain rearrangements, and dynamic molecular
        behavior that may remain hidden in conventional consensus
        reconstructions.

        Inputs and General Workflow

        The protocol requires a set of aligned particles together with a
        reference mask that defines the region of interest for variability
        analysis. The particles should already contain reliable alignment
        parameters because the protocol assumes that the dominant particle
        orientations and shifts have been accurately determined in previous
        refinement steps.

        The mask is biologically important because it determines which regions
        contribute to the variability calculation. Proper masking helps focus
        the analysis on meaningful structural regions while excluding solvent,
        noise, or poorly reconstructed areas. In many practical cryo-EM
        workflows, variability analysis is most informative when the mask
        isolates the flexible or functionally relevant region of the structure.

        Once the analysis is completed, the protocol produces a reference
        volume together with particles containing variability information that
        can later be explored using downstream visualization or display
        protocols.

        Biological Meaning of Variability Modes

        The variability modes generated by the protocol represent dominant
        patterns of structural motion or heterogeneity within the dataset.
        These modes are mathematically orthogonal descriptions of variability,
        but biologically they often correspond to interpretable conformational
        transitions.

        Examples include opening and closing motions, rotations of flexible
        domains, ligand-dependent rearrangements, or gradual transitions
        between assembly states. However, users should interpret the resulting
        modes carefully because not every variability component necessarily
        corresponds to a discrete biological state. Some modes may capture
        correlated noise, alignment uncertainty, or highly continuous motions
        that do not separate cleanly into distinct conformations.

        Number of Variability Modes

        The number of solved variability modes determines how extensively the
        conformational landscape is explored. Lower values focus on the most
        dominant structural motions, while larger values allow detection of
        more subtle heterogeneity patterns.

        In biological practice, a small number of modes is often sufficient to
        capture the major functional motions of a molecular complex. Increasing
        the number of modes may reveal additional flexibility but can also
        introduce components that are difficult to interpret biologically.
        Users are encouraged to begin with moderate values and evaluate the
        interpretability of each resulting mode.

        Iterative Optimization and Stability

        The protocol performs iterative optimization to estimate the principal
        variability components. The number of iterations influences both
        convergence quality and computational cost. More iterations may improve
        stability for difficult datasets, although excessively long
        optimization is not always necessary for biologically meaningful
        results.

        A stabilization parameter is also available to improve robustness
        during optimization. In datasets with strong noise, extreme
        flexibility, or unstable behavior, increasing stabilization may help
        suppress artifacts and improve interpretability of the resulting
        variability modes.

        Symmetry Considerations

        Symmetry can be applied during variability analysis when the molecular
        system possesses known structural symmetry. Correct symmetry handling
        improves consistency and signal quality while preserving biologically
        meaningful motions compatible with the symmetry definition.

        Nevertheless, biological caution is required because imposing symmetry
        may suppress asymmetric conformations or localized flexibility. For
        complexes with partially broken symmetry or asymmetric functional
        states, performing variability analysis without symmetry may provide a
        more realistic description of molecular behavior.

        Noise Models and Scale Treatment

        The protocol supports different approaches for modeling particle noise
        and intensity scaling. Depending on the dataset characteristics,
        different noise assumptions may improve stability and sensitivity to
        structural variability.

        A white noise model may work well for some datasets with relatively
        uniform background statistics, whereas colored noise models may better
        represent experimental conditions in other cases. Similarly,
        per-particle scaling can either be ignored, inherited from previous
        processing, or optimized dynamically during analysis.

        These parameters mainly influence numerical stability and robustness.
        For most biological users, the default settings provide a suitable
        starting point, while advanced optimization may be reserved for
        particularly challenging datasets.

        Filtering and Resolution Control

        Resolution filtering helps define the spatial frequency range used
        during variability estimation. Filtering is biologically important
        because conformational motions are often dominated by low- or
        intermediate-resolution structural changes rather than atomic-level
        details.

        Applying an appropriate filter may suppress high-frequency noise and
        improve interpretability of large-scale structural transitions.
        However, excessive filtering can oversimplify the conformational
        landscape and obscure localized structural rearrangements.

        Outputs and Their Interpretation

        The protocol produces a representative volume together with a particle
        dataset enriched with variability information. These outputs preserve
        the original alignment framework and are intended for downstream
        visualization and interpretation using dedicated variability display
        tools.

        The resulting variability information should be interpreted as a
        description of structural trends within the particle population rather
        than a definitive classification into rigid states. Continuous motions,
        compositional heterogeneity, and partially overlapping conformations
        are common outcomes in biological cryo-EM datasets.

        Practical Recommendations

        For most biological studies, it is advisable to begin with a moderate
        number of variability modes and carefully inspect the resulting motions
        before increasing complexity. Proper masking is often the most
        important factor for obtaining meaningful results, especially in
        flexible assemblies or multi-domain proteins.

        When interpreting variability, users should compare observed motions
        with known biochemical data, structural models, or functional
        hypotheses. Structural changes that are reproducible, spatially
        coherent, and biologically plausible are more likely to reflect real
        conformational dynamics.

        Highly flexible systems may benefit from larger masks and gentler
        filtering, whereas smaller or more rigid complexes often produce
        cleaner and easier-to-interpret variability components.

        Final Perspective

        Continuous heterogeneity analysis has become a central component of
        modern cryo-EM because many biological systems operate through dynamic
        structural transitions rather than fixed conformations. This protocol
        provides a framework for exploring those motions directly from aligned
        particle datasets, enabling researchers to investigate molecular
        flexibility, functional transitions, and conformational landscapes in
        a biologically meaningful manner.
    """
    _label = '3D variability Analysis '
    _devStatus = BETA

    # --------------------------- DEFINE param functions ----------------------
    def _defineFileNames(self):
        """ Centralize how files are called within the protocol. """
        myDict = {
                  'input_particles': self._getTmpPath('input_particles.star'),
                  'out_particles': self._getPath() + '/output_particle.star',
                  'stream_log': self._getPath()+'/stream.log'
                  }
        self._updateFilenamesDict(myDict)

    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('inputParticles', PointerParam,
                      pointerClass='SetOfParticles',
                      label="Input particles", important=True,
                      validators=[Positive],
                      help='Select the input images from the project.')
        form.addParam('refMask', PointerParam, pointerClass='VolumeMask',
                      default=None,
                      label='Input Mask',
                      allowsNull=False,
                      help='Mask raw data')

        form.addParallelSection(threads=1, mpi=1)

        # --------------[3D Variability]---------------------------

        form.addSection(label='3D Variability')
        form.addParam('var_K', IntParam, default=3,
                      label="Number of modes to solve",
                      help='The number of orthogonal principle modes (i.e. '
                           'eigenvectors of the 3D covariance) to solve.')

        form.addParam('var_num_iterations', IntParam, default=20,
                      validators=[Positive],
                      label="Number of iterations",
                      help='Number of iterations')

        # form.addParam('var_N', FloatParam, default=-1,
        #               expertLevel=LEVEL_ADVANCED,
        #               label="Refinement box size (Voxels)",
        #               help='The volume size to use for refinement. If this is '
        #                    '-1, use the full image size. Otherwise images '
        #                    'are automatically downsampled')

        addSymmetryParam(form)

        # form.addParam('var_num_particles', IntParam, default=None,
        #               label="Only use this many particles")

        form.addParam('var_filter_res', FloatParam, default=None,
                      validator=[Positive],
                      label="Filter resolution (A)",
                      help='Resolution at which results are filtered')

        form.addParam('var_filter_order', FloatParam, default=1.5,
                      validators=[Positive],
                      label="Filter order",
                      help='Order of filter')

        # form.addParam('var_highpass_res', StringParam, default='',
        #               expertLevel=LEVEL_ADVANCED,
        #               label="Highpass resolution (A)",
        #               help='Resolution below which variability is ignored')

        form.addParam('var_highpass_order', FloatParam, default=8,
                      validators=[Positive],
                      label="Highpass order",
                      help='Order of filter')

        form.addParam('var_use_gramschmidt', BooleanParam, default=True,
                      label="Use Gram-Schmidt",
                      help='Order of filter')

        form.addParam('var_use_white_noise', BooleanParam, default=False,
                      label="Use white noise model",
                      help='Use a white noise model (default) instead of a '
                           'colored noise model. One or the other may work '
                           'better depending on the dataset.')

        form.addParam('var_use_scales', EnumParam,
                      choices=['none', 'input', 'optimal'],
                      default=2,
                      label="Per-particle scale",
                      help='How to treat per-particle scale factors. No scales '
                           'means all particles have scale 1.0 (useful for very '
                           'small particles or strange cases). Input scales '
                           'means to use the input scale factors (which may '
                           'have come from another refinement). Optimal means '
                           'to compute per-particle optimal scales on the fly '
                           'during 3D variability.')

        form.addParam('var_lambda', FloatParam, default=0.01,
                      validators=[Positive],
                      label="Lambda",
                      help='Stabilizing coefficient - try larger values if '
                           'optimization diverges and creates artefacts. '
                           'In v2.12 this was changed to a normalized '
                           'fractional value, where 0.01 should work for '
                           'almost all datasets.')
        # --------------[Compute settings]---------------------------
        form.addSection(label="Compute settings")
        addComputeSectionParams(form, allowMultipleGPUs=False)

    # --------------------------- INSERT steps functions -----------------------
    def _insertAllSteps(self):
        self._defineFileNames()
        self._defineParamsName()
        self._initializeCryosparcProject()
        self._insertFunctionStep(self.convertInputStep)
        self._insertFunctionStep(self.processStep)
        self._insertFunctionStep(self.createOutputStep)

    # --------------------------- STEPS functions ------------------------------
    def processStep(self):
        self.info(pwutils.yellowStr("3D Variability started..."))
        self.doRun3DVariability()

    def createOutputStep(self):
        """
        Create the protocol output. Convert cryosparc file to Relion file
        """
        self._initializeUtilsVariables()
        csOutputFolder = os.path.join(self.projectDir.get(),
                                      self.run3DVariability.get())
        csParticlesName = (getOutputPreffix(self.projectName.get()) +
                           self.run3DVariability.get() + "_particles.cs")

        csFile = os.path.join(csOutputFolder, csParticlesName)

        # Copy the particles to scipion output folder
        os.system("cp -r " + csFile + " " + self._getExtraPath())
        csFile = os.path.join(self._getExtraPath(), csParticlesName)

        outputStarFn = self._getFileName('out_particles')
        argsList = [csFile, outputStarFn]

        convertCs2Star(argsList)

        fnVolName = (getOutputPreffix(self.projectName.get()) +
                     self.run3DVariability.get() + "_map.mrc")

        fnVol = os.path.join(csOutputFolder, fnVolName)

        # Copy the volumes to extra folder
        os.system("cp -r " + fnVol + " " + self._getExtraPath())
        fnVol = os.path.join(self._getExtraPath(), fnVolName)

        imgSet = self._getInputParticles()
        vol = Volume()
        vol.setFileName(fnVol)
        vol.setSamplingRate(calculateNewSamplingRate(vol.getDim(),
                                                     imgSet.getSamplingRate(),
                                                     imgSet.getDim()))
        outImgSet = self._createSetOfParticles()
        outImgSet.copyInfo(imgSet)
        self._fillDataFromIter(outImgSet)

        self._defineOutputs(outputVolume=vol)
        self._defineSourceRelation(self.inputParticles.get(), vol)
        self._defineOutputs(outputParticles=outImgSet)
        self._defineTransformRelation(self.inputParticles.get(), outImgSet)

    #  ----------------------------UTILS functions --------------------------

    def cleanTmp(self):
        """ Delete all files and subdirectories under Tmp folder. For this
        protocol we need to keep the tmp folder content"""
        pass

    def _validate(self):
        validateMsgs = cryosparcValidate()
        if not validateMsgs:
            validateMsgs = gpusValidate(self.getGpuList(), checkSingleGPU=True)
            if not validateMsgs:
                particles = self._getInputParticles()
                if not particles.hasCTF():
                    validateMsgs.append("The Particles has not associated a "
                                        "CTF model")
        return validateMsgs

    def _summary(self):
        summary = []
        if (not hasattr(self, 'outputVolume') or
                not hasattr(self, 'outputParticles') or
                not hasattr(self, 'outputFSC')):
            summary.append("Output objects not ready yet.")
        else:
            summary.append("Input Particles: %s" %
                           self.getObjectTag('inputParticles'))
            summary.append("Input Volume: %s" %
                           self.getObjectTag('refVolume'))
            summary.append("Input Mask: %s" %
                           self.getObjectTag('refMask'))
            summary.append("Symmetry: %s" %
                           getSymmetry(self.symmetryGroup.get(),
                                       self.symmetryOrder.get())
                           )
            summary.append("------------------------------------------")
            summary.append("Output particles %s" %
                           self.getObjectTag('outputParticles'))
            summary.append("Output volume %s" %
                           self.getObjectTag('outputVolume'))
        return summary

    # -------------------------- UTILS functions ------------------------------

    def _fillDataFromIter(self, imgSet):
        outImgsFn = 'particles@' + self._getFileName('out_particles')
        imgSet.setAlignmentProj()
        imgSet.copyItems(self._getInputParticles(),
                         updateItemCallback=self._createItemMatrix,
                         itemDataIterator=emtable.Table.iterRows(
                             fileName=outImgsFn))

    def _createItemMatrix(self, particle, row):
        createItemMatrix(particle, row, align=ALIGN_PROJ)
        setCryosparcAttributes(particle, row,
                               RELIONCOLUMNS.rlnRandomSubset.value)

    def _defineParamsName(self):
        """ Define a list with all protocol parameters names"""
        self._paramsName = ['var_K',
                            'var_filter_res',
                            'var_filter_order',
                            'var_highpass_order',
                            'var_use_gramschmidt',
                            'var_use_white_noise',
                            'var_use_scales',
                            'var_num_iterations',
                            'var_lambda',
                            'compute_use_ssd',
                            'var_symmetry']
        self.lane = str(self.getAttributeValue('compute_lane'))

    def doRun3DVariability(self):
        """
        :return:
        """
        className = "var_3D"
        input_group_conect = {"particles": str(self.particles),
                              "mask": str(self.mask)}
        params = {}

        for paramName in self._paramsName:
            if (paramName != 'var_symmetry' and
                    paramName != 'var_use_scales'):
                params[str(paramName)] = str(self.getAttributeValue(paramName))
            elif paramName == 'var_symmetry':
                symetryValue = getSymmetry(self.symmetryGroup.get(),
                                           self.symmetryOrder.get())
                params[str(paramName)] = symetryValue
            elif paramName == 'var_use_scales':
                params[str(paramName)] = str(VAR_USE_SCALES[self.var_use_scales.get()])

        # Determinate the GPUs to use (in dependence of
        # the cryosparc version)
        try:
            if not self.useQueueForSteps() and not self.useQueue():  # not using queue system
                gpusToUse = self.getGpuList()
            else:  # using queue system
                gpusToUse = False
        except Exception:
            gpusToUse = False

        self.run3DVariability = enqueueJob(className, self.projectName.get(),
                                           self.workSpaceName.get(),
                                           str(params).replace('\'', '"'),
                                           str(input_group_conect).replace('\'',
                                                                           '"'),
                                           self.lane, gpusToUse)

        self.currenJob.set(self.run3DVariability.get())
        self._store(self)

        waitForCryosparc(self.projectName.get(), self.run3DVariability.get(),
                         "An error occurred in the 3D Variability process. "
                         "Please, go to cryosPARC software for more "
                         "details.", self)



